---
title: "HW-4"
author: "Dewen Xu, Muyao Sun, Liwen Zhang, Xialingzi Jin"
date: "10/12/2016"
output: html_document
---


###Task 1 - Sock Shiny App
We create two files called ui.R and server.R. These two files contain the implementation of my Shiny app from users' interactive part and server part. 
In the ui file, we create two main tabs describing the plots and summary statistics results. On the left penal, we create the range of data values and prior value that users can interact with. The data values include the number of paired socks ranging from 0 to 100, and number of singleton socks from 0 to 100. We include four prior values: prior mean and prior standard deviation from 10 to 100. shape 1 alpha and shape 2 beta from 1 to 100. The plots and summary statistics will change simultaneously when the user interact with different values. 
In the server file, we create the function based on the calculation introduced on the blog link. By applying two reactive functions to generate simulation socks called sock_sim and posterior samples called post_samples. In sock_sim, we replicate the times of simulation that use input, to generate simulated results with six values: n_socks(number of total socks), prop_pairs(proportion of pairs socks), n_pairs(number of pairs in the laundry), n_odds(number of singleton socks in laundry),  
unique(number of singleton socks picked out), and pairs(number of pairs picked out). The post_samples is generated by subsetting based on sock_sim, filtering out the unique value corresponding to user input number of singleton socks, and pairs value corresponding to user input number of pairs socks. 
Finally, we output the plots and summary statistics including mean, median and 95% confidence interval for each value inside sim_socks and post_samples.

###Task 2 - We need speed. Speed’s what we need.
The purpose of task 2 is to test how efficient our code is. In our original **ui.R** code, we used `replicate` to simulate the total number of socks. However, using `replicate` is very inefficient since it just treats our code as whole and puts into 1 core. When we adjust our prior parameters in our app, the appearance of updated graph is slow. Therefore, we decide to abandon the method `replicate` and to use `mcmapply` instead since it cuts our code into several parts and sends them to different cores, then puts the results back together. More specific, writing a function to generate one total number of socks, then set how many times to iterate and apply `mcmapply` on these functions. In this case, it takes much less times than only use 1 core which `replicate` does. At this time, when we adjust parameters of priors on our app, the updated results will show quickly.  







